on:
  workflow_dispatch:
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Excavate
        uses: Ash258/Scoop-GithubActions@stable-win
        env:
          GITHUB_EVENT_NAME: schedule
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: "1"
