on:
  workflow_dispatch:
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Excavate
        uses: Ash258/Scoop-GithubActions@stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: "1"
