on:
  issue_comment:
    types: [created]
name: Commented Pull Request
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: PullRequestHandler
        uses: frostming/scoop-action@main
        if: startsWith(github.event.comment.body, '/verify') && contains(fromJSON('["frostming"]'), github.event.comment.user.login)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
