on:
  pull_request:
    types: [opened]
name: Pull Requests
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: PullRequestHandler
        uses: frostming/scoop-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
